In [133]:
import sys, numpy as np
from keras.datasets import mnist

In [134]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [135]:
x_train.shape

(60000, 28, 28)

In [136]:
x_test.shape

(10000, 28, 28)

In [137]:
# update 28x28 image to 1 vector of length 784
# divide by 255 to normalize values between 0-1 (original values were 0-255)
images, labels = (x_train[0:1000].reshape(1000, 28*28) / 255, y_train[0:1000]) 

In [138]:
images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [139]:
images.shape

(1000, 784)

In [140]:
labels.shape

(1000,)

In [141]:
labels

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1, 5, 7, 1, 7, 1, 1, 6, 3, 0, 2,
       9, 3, 1, 1, 0, 4, 9, 2, 0, 0, 2, 0, 2, 7, 1, 8, 6, 4, 1, 6, 3, 4,
       5, 9, 1, 3, 3, 8, 5, 4, 7, 7, 4, 2, 8, 5, 8, 6, 7, 3, 4, 6, 1, 9,
       9, 6, 0, 3, 7, 2, 8, 2, 9, 4, 4, 6, 4, 9, 7, 0, 9, 2, 9, 5, 1, 5,
       9, 1, 2, 3, 2, 3, 5, 9, 1, 7, 6, 2, 8, 2, 2, 5, 0, 7, 4, 9, 7, 8,
       3, 2, 1, 1, 8, 3, 6, 1, 0, 3, 1, 0, 0, 1, 7, 2, 7, 3, 0, 4, 6, 5,
       2, 6, 4, 7, 1, 8, 9, 9, 3, 0, 7, 1, 0, 2, 0, 3, 5, 4, 6, 5, 8, 6,
       3, 7, 5, 8, 0, 9, 1, 0, 3, 1, 2, 2, 3, 3, 6, 4, 7, 5, 0, 6, 2, 7,
       9, 8, 5, 9, 2, 1, 1, 4, 4, 5, 6, 4, 1, 2, 5, 3, 9, 3, 9, 0, 5, 9,
       6, 5, 7, 4, 1, 3, 4, 0, 4, 8, 0, 4, 3, 6, 8,

In [142]:
one_hot_labels = np.zeros((len(labels), 10))

In [143]:
one_hot_labels.shape

(1000, 10)

In [144]:
for i,l in enumerate(labels): #update labels... w/ one-hot encoding
    one_hot_labels[i][l] = 1
labels = one_hot_labels

In [145]:
labels.shape

(1000, 10)

In [146]:
labels[0] # 1 in 5 location now b/c 5 was the first value in labels previously (above)

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [147]:
test_images = x_test.reshape(len(x_test),28*28) / 255

In [148]:
test_images.shape

(10000, 784)

In [149]:
test_labels = np.zeros((len(y_test),10))

In [150]:
for i,l in enumerate(y_test): #one-hot encoding...
    test_labels[i][l] = 1

In [151]:
np.random.seed(1)
relu = lambda x:(x>=0) * x
relu2deriv = lambda x: x>=0
alpha, iterations, hidden_size, pixels_per_image, num_labels = \
    (0.005, 350, 40, 784, 10)

In [152]:
weights_0_1 = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
# we only 

In [153]:
weights_0_1.shape

(784, 40)

In [154]:
weights_0_1[0]

array([-0.0165956 ,  0.0440649 , -0.09997713, -0.03953349, -0.07064882,
       -0.08153228, -0.06274796, -0.03088785, -0.02064651,  0.00776335,
       -0.0161611 ,  0.0370439 , -0.05910955,  0.07562349, -0.09452248,
        0.0340935 , -0.01653904,  0.01173797, -0.07192261, -0.0603797 ,
        0.06014891,  0.09365232, -0.03731516,  0.03846452,  0.07527783,
        0.07892133, -0.08299116, -0.09218904, -0.06603392,  0.0756285 ,
       -0.08033063, -0.01577847,  0.09157791,  0.00663306,  0.03837542,
       -0.03689687,  0.03730019,  0.06692513, -0.09634234,  0.05002886])

In [155]:
weights_1_2 = 0.2*np.random.random((hidden_size, num_labels)) - 0.1

In [156]:
for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(len(images)):
        layer_0 = images[i:i+1]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        error += ((labels[i:i+1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == np.argmax(labels[i:i+1]))
        
        layer_2_delta = labels[i:i+1] - layer_2
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
        
    sys.stdout.write("\r"+ \
                     " I:"+str(j)+ \
                     " Error:"+str(error/float(len(images)))[0:5] + \
                     " Correct:" + str(correct_cnt/float(len(images))))

 I:349 Error:[[0.0 Correct:1.099

In [157]:
# how do we do on an image we haven't seen before?

In [158]:
if(j % 10 == 0 or j == iterations-1):
    error, correct_cnt = (0.0, 0)
    for i in range(len(test_images)):
        layer_0 = test_images[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        
        error += np.sum((test_labels[i:i+1] - layer_2)**2)
        correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))
    
    sys.stdout.write(" Test-Err:" + str(error/float(len(test_images)))[0:5] + \
                     " Test-Acc:" + str(correct_cnt/float(len(test_images))))
    print()

 Test-Err:0.653 Test-Acc:0.7073


In [159]:
# oof

In [160]:
# we can view the weights of a NN as a high dimensional shape - shape molds around data as we train. slight diff in shape
# can result in bad prediction

# regularization is a subfield of methods for getting a model to genearlize to new datapoints (instead of just memorizing
# training data)

In [161]:
# industry standard regularization: dropout
#    during training randomly set neurons in the network to 0. this causes the nn to train exclusively using 
#    random subsections of the network. Dropout makes a big network acct like a little one by randomly training
#    subsections of the network at a time - little networks don't overfit. smaller networks have less 
#    "expresive power" - they can't latch on to more granular details (noise) that can cause overfitting.
#    only have room to capture big obvious high-level features.

# basically a form of training a bunch of networks and averaging them.

# if you train 100 nns (all initialized randomly) they will tend to latch onto different noise but similar broad signal
# thus when they make mistakes they will make differing mistakes, and these differing mistakes tend to cancel out
# revealing the signal.

In [169]:
# with dropout
        #     randomly turn off nodes and multiply by 2 b/c sum was cut in half by all the off nodes
        #     we want "volume" of layer_1 to be the same between training and testing despite dropout

alpha, iterations, hidden_size = (0.005, 300, 100)
pixels_per_image, num_labels = (784, 10)
weights_0_1 = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
weights_1_2 = 0.2*np.random.random((hidden_size, num_labels)) - 0.1

for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(len(images)):
        layer_0 = images[i:i+1]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        dropout_mask = np.random.randint(2, size=layer_1.shape) # 
        layer_1 *= dropout_mask * 2 # dropout
        layer_2 = np.dot(layer_1, weights_1_2)
        
        error += np.sum((labels[i:i+1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == np.argmax(labels[i:i+1]))
        
        layer_2_delta = (labels[i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
        # DROPOUT AGAIN
        layer_1_delta *= dropout_mask
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
        
    if (j%10 == 0):
        test_error = 0.0
        test_correct_cnt = 0
        
        for i in range(len(test_images)):
            layer_0 = test_images[i:i+1]
            layer_1 = relu(np.dot(layer_0, weights_0_1))
            layer_2 = np.dot(layer_1, weights_1_2)
            
            test_error += np.sum((test_labels[i:i+1] - layer_2) ** 2)
            test_correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))
            
        sys.stdout.write(
            f"\ni:{j}"
            f" test-err:{test_error/float(len(test_images)):.5}"
            f" test-acc:{test_correct_cnt/float(len(test_images))}"
            f" train-err:{error/float(len(images)):.5}"
            f" train-acc:{correct_cnt/float(len(images))}"
        )


i:0 test-err:0.65217 test-acc:0.6492 train-err:0.91715 train-acc:0.389
i:10 test-err:0.44305 test-acc:0.7971 train-err:0.44493 train-acc:0.806
i:20 test-err:0.41669 test-acc:0.8201 train-err:0.42812 train-acc:0.826
i:30 test-err:0.41382 test-acc:0.8157 train-err:0.39975 train-acc:0.839
i:40 test-err:0.41227 test-acc:0.8276 train-err:0.39331 train-acc:0.837
i:50 test-err:0.409 test-acc:0.827 train-err:0.37683 train-acc:0.851
i:60 test-err:0.40459 test-acc:0.8284 train-err:0.36824 train-acc:0.878
i:70 test-err:0.39275 test-acc:0.8345 train-err:0.35609 train-acc:0.867
i:80 test-err:0.39578 test-acc:0.8309 train-err:0.35862 train-acc:0.877
i:90 test-err:0.39184 test-acc:0.828 train-err:0.34455 train-acc:0.879
i:100 test-err:0.3931 test-acc:0.8268 train-err:0.34609 train-acc:0.893
i:110 test-err:0.40145 test-acc:0.826 train-err:0.34037 train-acc:0.883
i:120 test-err:0.39769 test-acc:0.8261 train-err:0.33537 train-acc:0.888
i:130 test-err:0.39774 test-acc:0.8273 train-err:0.33964 train-acc:

In [163]:
# 81% test-acc compared to 71% without dropout

In [168]:
# batch gradient descent
#     instead of training on 1 example at a time let's train 100 training examples at a time and average the weight updates
#     among all 100 examples.

batch_size = 100
alpha, iterations = (0.001, 300)
pixels_per_image, num_labels, hidden_size = (784, 10, 100)

weights_0_1 = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
weights_1_2 = 0.2*np.random.random((hidden_size, num_labels)) - 0.1

for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(int(len(images) / batch_size)):
        batch_start, batch_end = ((i * batch_size), ((i+1)*batch_size))
        
        layer_0 = images[batch_start:batch_end]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask * 2
        layer_2 = np.dot(layer_1, weights_1_2)
        
        error += np.sum((labels[batch_start:batch_end] - layer_2) ** 2)
        for k in range(batch_size):
            correct_cnt += int(np.argmax(layer_2[k:k+1]) == \
                np.argmax(labels[batch_start+k:batch_start+k+1]))
            
            layer_2_delta = (labels[batch_start:batch_end]-layer_2) / batch_size 
                                                        
            layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
            layer_1_delta *= dropout_mask
            
            weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
            weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
            
    if(j%10 == 0):
        test_error = 0.0
        test_correct_cnt = 0 
        
        for i in range(len(test_images)):
            layer_0 = test_images[i:i+1]
            layer_1 = relu(np.dot(layer_0, weights_0_1))
            layer_2 = np.dot(layer_1, weights_1_2)
            
        sys.stdout.write(
            f"\ni:{j}"
            f" test-err:{test_error/float(len(test_images)):.5}"
            f" test-acc:{test_correct_cnt/float(len(test_images))}"
            f" train-err:{error/float(len(images)):.5}"
            f" train-acc:{correct_cnt/float(len(images))}"
        )
            


i:0 test-err:0.0 test-acc:0.0 train-err:1.2041 train-acc:0.171
i:10 test-err:0.0 test-acc:0.0 train-err:0.57557 train-acc:0.717
i:20 test-err:0.0 test-acc:0.0 train-err:0.50938 train-acc:0.755
i:30 test-err:0.0 test-acc:0.0 train-err:0.47461 train-acc:0.769
i:40 test-err:0.0 test-acc:0.0 train-err:0.44688 train-acc:0.797
i:50 test-err:0.0 test-acc:0.0 train-err:0.44398 train-acc:0.789
i:60 test-err:0.0 test-acc:0.0 train-err:0.42499 train-acc:0.822
i:70 test-err:0.0 test-acc:0.0 train-err:0.4269 train-acc:0.809
i:80 test-err:0.0 test-acc:0.0 train-err:0.42301 train-acc:0.814
i:90 test-err:0.0 test-acc:0.0 train-err:0.42454 train-acc:0.811
i:100 test-err:0.0 test-acc:0.0 train-err:0.40636 train-acc:0.844
i:110 test-err:0.0 test-acc:0.0 train-err:0.4042 train-acc:0.832
i:120 test-err:0.0 test-acc:0.0 train-err:0.40836 train-acc:0.837
i:130 test-err:0.0 test-acc:0.0 train-err:0.40343 train-acc:0.83
i:140 test-err:0.0 test-acc:0.0 train-err:0.39914 train-acc:0.839
i:150 test-err:0.0 test-

In [ ]:
# smoother training accuracy. individual training examples are very noisy in terms of the weight updates they generate
# averaging them makes for smoother learning process. b/c it takes an average it can take bigger steps.
# generally researchers pick numbers randomly until they find a batch_size/alpha pair that "seems to work well"